/**
 * Updates and packs the canonical trusted-setup JSON.
 *
 * Usage:
 *   pnpm trusted-setups:update <c-kzg release tag>
 *   pnpm trusted-setups:build
 *   pnpm trusted-setups:check
 */

import * as crypto from 'node:crypto'
import * as fs from 'node:fs'
import * as path from 'node:path'

const root = path.resolve(import.meta.dirname, '../..')
const input = path.join(root, 'src/trusted-setups/internal/setups/mainnet.json')
const metadata = path.join(
  root,
  'src/trusted-setups/internal/setups/mainnet.source.json',
)
const output = path.join(root, 'src/trusted-setups/internal/setups/mainnet.ts')

type Setup = {
  g1_lagrange: readonly string[]
  g1_monomial: readonly string[]
  g2_monomial: readonly string[]
}

type Source = {
  path: string
  repository: string
  setupSha256: string
  sourceSha256: string
  tag: string
}

function digest(value: string) {
  return crypto.createHash('sha256').update(value).digest('hex')
}

function encode(
  name: keyof Setup,
  points: readonly string[],
  count: number,
  size: number,
) {
  if (points.length !== count)
    throw new Error(`\`${name}\` must contain ${count} points.`)
  const pattern = new RegExp(`^0x[0-9a-f]{${size * 2}}$`)
  for (const [index, point] of points.entries())
    if (!pattern.test(point))
      throw new Error(
        `\`${name}[${index}]\` must be a lowercase ${size}-byte hex value.`,
      )
  return Buffer.concat(
    points.map((point) => Buffer.from(point.slice(2), 'hex')),
  ).toString('base64')
}

function buildModule(setup: Setup) {
  const g1Lagrange = encode('g1_lagrange', setup.g1_lagrange, 4_096, 48)
  const g1Monomial = encode('g1_monomial', setup.g1_monomial, 4_096, 48)
  const g2Monomial = encode('g2_monomial', setup.g2_monomial, 65, 96)
  return `// Generated by \`pnpm trusted-setups:build\`. Do not edit.
//
// Packed from src/trusted-setups/internal/setups/mainnet.json.
// \`pnpm trusted-setups:check\` regenerates this module and fails if it differs.

/** Base64-encoded G1 points in Lagrange form. */
export const g1Lagrange =
  '${g1Lagrange}'

/** Base64-encoded G1 points in monomial form. */
export const g1Monomial =
  '${g1Monomial}'

/** Base64-encoded G2 points in monomial form. */
export const g2Monomial =
  '${g2Monomial}'
`
}

function parse(source: string): Setup {
  const lines = source.trim().split(/\r?\n/)
  const g1Count = Number(lines[0])
  const g2Count = Number(lines[1])
  if (g1Count !== 4_096 || g2Count !== 65)
    throw new Error(
      'The c-kzg setup must declare 4096 G1 points and 65 G2 points.',
    )
  if (lines.length !== 2 + g1Count * 2 + g2Count)
    throw new Error(
      'The c-kzg setup must contain G1 Lagrange, G2 monomial, and G1 monomial points.',
    )

  const g1LagrangeEnd = 2 + g1Count
  const g2MonomialEnd = g1LagrangeEnd + g2Count
  const toHex = (point: string) => `0x${point}`
  return {
    g1_monomial: lines.slice(g2MonomialEnd).map(toHex),
    g1_lagrange: lines.slice(2, g1LagrangeEnd).map(toHex),
    g2_monomial: lines.slice(g1LagrangeEnd, g2MonomialEnd).map(toHex),
  }
}

function serialize(value: unknown) {
  return `${JSON.stringify(value, null, 2)}\n`
}

async function update(tag: string) {
  if (!/^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(tag))
    throw new Error(
      'Pass an explicit c-kzg release tag, for example `pnpm trusted-setups:update v2.1.8`.',
    )

  const repository = 'https://github.com/ethereum/c-kzg-4844'
  const sourcePath = 'src/trusted_setup.txt'
  const url = `https://raw.githubusercontent.com/ethereum/c-kzg-4844/${tag}/${sourcePath}`
  const response = await fetch(url)
  if (!response.ok)
    throw new Error(
      `Unable to fetch c-kzg ${tag} trusted setup (${response.status}).`,
    )

  const source = await response.text()
  const setup = parse(source)
  const json = serialize(setup)
  const module = buildModule(setup)
  const provenance: Source = {
    path: sourcePath,
    repository,
    setupSha256: digest(json),
    sourceSha256: digest(source),
    tag,
  }

  fs.writeFileSync(input, json)
  fs.writeFileSync(metadata, serialize(provenance))
  fs.writeFileSync(output, module)
  console.log(`Updated mainnet from c-kzg ${tag}.`)
}

const updateIndex = process.argv.indexOf('--update')
if (updateIndex !== -1) {
  const tag = process.argv[updateIndex + 1]
  if (!tag)
    throw new Error(
      'Pass an explicit c-kzg release tag, for example `pnpm trusted-setups:update v2.1.8`.',
    )
  await update(tag)
  process.exit(0)
}

const json = fs.readFileSync(input, 'utf8')
const provenance = JSON.parse(fs.readFileSync(metadata, 'utf8')) as Source
if (digest(json) !== provenance.setupSha256)
  throw new Error(
    'The mainnet setup does not match its source metadata. Run `pnpm trusted-setups:update <tag>`.',
  )
const source = buildModule(JSON.parse(json) as Setup)

if (process.argv.includes('--check')) {
  const committed = fs.existsSync(output) ? fs.readFileSync(output, 'utf8') : ''
  if (committed !== source) {
    console.error(
      'The packed mainnet trusted setup is out of date. Run `pnpm trusted-setups:build`.',
    )
    process.exit(1)
  }
  console.log('✔ mainnet')
} else {
  fs.writeFileSync(output, source)
  console.log(`Wrote ${path.relative(root, output)}.`)
}
