/**
 * Compiles the C targets in `wasm/targets.ts` into base64 TypeScript modules.
 *
 * The base64 module *is* the committed artifact: it ships through the normal
 * build with no bundler or asset-pipeline configuration, and loads identically
 * in Node, Bun, Deno, browsers and edge runtimes.
 *
 * `scripts/wasm/build.ts` and `check.ts` are the entrypoints. This module only
 * builds; it does not write.
 */

import * as child_process from 'node:child_process'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { type Target, targets } from '../../wasm/targets.js'
import { type Resolved, resolve, root, toolchain } from './toolchain.js'

const buildDir = path.join(root, 'wasm/.build')

/** Flags shared by every target. */
function commonFlags(toolchain: Resolved) {
  return [
    '--target=wasm32',
    '-O3',
    '-flto', // full LTO; ThinLTO is not reliably deterministic
    '-nostdlib',
    '-ffreestanding',
    '-fno-builtin',
    '-fno-exceptions',
    '-fno-unwind-tables',
    '-fno-stack-protector',
    '-Werror=implicit-function-declaration',
    '-Wl,--no-entry',
    '-Wl,--strip-all',
    '-Wl,--gc-sections',
    '-Wl,--lto-O3',
    '-Wl,--export-memory',
    // Exports are declared with `__attribute__((export_name(...)))` in the C, so
    // the export list stays next to the code that defines it.
    `-I${path.join(root, 'wasm/shim')}`,
    `-I${path.join(root, 'wasm/src')}`,
    ...(toolchain.clangRtDir
      ? [`-L${toolchain.clangRtDir}`, '-lclang_rt.builtins-wasm32']
      : []),
  ]
}

function targetFlags(target: Target) {
  return [
    ...(target.includes?.map((include) => `-I${path.join(root, include)}`) ??
      []),
    ...Object.entries(target.defines ?? {}).map(
      ([key, value]) => `-D${key}=${value}`,
    ),
    ...(target.cflags ?? []),
    `-Wl,--initial-memory=${target.initialMemory}`,
    ...(target.maxMemory ? [`-Wl,--max-memory=${target.maxMemory}`] : []),
    ...(target.stackSize ? [`-Wl,-z,stack-size=${target.stackSize}`] : []),
  ]
}

/**
 * Asserts the artifact carries no toolchain fingerprint.
 *
 * A surviving `producers` section embeds the compiler version string, which
 * would make the bytes depend on the toolchain in a way `--strip-all` was
 * supposed to remove -- and it would do so silently.
 */
function assertStripped(bytes: Uint8Array, name: string) {
  const text = Buffer.from(bytes).toString('latin1')
  for (const section of ['producers', 'target_features'])
    if (text.includes(section))
      throw new Error(
        `\`${name}\` still contains a \`${section}\` custom section. Artifacts must not embed toolchain metadata.`,
      )
}

function template(target: Target, bytes: Uint8Array, toolchainVersion: string) {
  const base64 = Buffer.from(bytes).toString('base64')
  const extra = Object.entries(target.extra ?? {})
    .map(
      ([key, value]) =>
        `\n/** Constant shared with the module's C source. */\nexport const ${key} = ${value}\n`,
    )
    .join('')
  return `// Generated by \`pnpm wasm:build --target=${target.name}\`. Do not edit.
//
// Compiled from ${target.sources.join(', ')}
// with ${toolchainVersion} + binaryen ${toolchain.binaryen}.
//
// \`pnpm wasm:check\` rebuilds this file and fails if the bytes differ, so any
// change to the C or to \`wasm/targets.ts\` must be followed by \`pnpm wasm:build\`.

/** Base64-encoded WASM binary. */
export const wasmBase64 =
  '${base64}'
${extra}`
}

async function build(target: Target, toolchain: Resolved) {
  fs.mkdirSync(buildDir, { recursive: true })
  const raw = path.join(buildDir, `${target.name}.raw.wasm`)
  const optimized = path.join(buildDir, `${target.name}.wasm`)

  child_process.execFileSync(
    toolchain.clang,
    [
      ...commonFlags(toolchain),
      ...targetFlags(target),
      '-o',
      raw,
      ...target.sources.map((source) => path.join(root, source)),
    ],
    { stdio: 'inherit' },
  )

  child_process.execFileSync(
    toolchain.wasmOpt,
    [
      ...(target.wasmOpt ?? ['-O4']),
      // Both sections record how the module was compiled rather than what it
      // does, and both vary with the toolchain -- so they are stripped to keep
      // the bytes reproducible. `assertStripped` verifies they are gone.
      '--strip-producers',
      '--strip-target-features',
      raw,
      '-o',
      optimized,
    ],
    { stdio: 'inherit' },
  )

  const bytes = new Uint8Array(fs.readFileSync(optimized))
  assertStripped(bytes, target.name)

  if (bytes.length > target.maxBytes)
    throw new Error(
      `\`${target.name}\` is ${bytes.length} bytes, over its ${target.maxBytes} byte budget. Shrink it, or raise \`maxBytes\` in \`wasm/targets.ts\` deliberately.`,
    )

  return {
    bytes,
    source: template(target, bytes, toolchain.version),
  }
}

/** Every C target name, for selection and error messages. */
export const names = targets.map((target) => target.name)

/**
 * Compiles the selected C targets and returns their generated modules, keyed by
 * repository-relative path.
 */
export async function buildC(
  selection?: readonly string[],
): Promise<Record<string, string>> {
  // An omitted selection means every target; an empty one means none. Conflating
  // the two would make `--target=evm2` rebuild all of C.
  const selected =
    selection === undefined
      ? targets
      : targets.filter((target) => selection.includes(target.name))
  if (!selected.length) return {}

  const toolchain = await resolve()
  const files: Record<string, string> = {}
  for (const target of selected) {
    const { bytes, source } = await build(target, toolchain)
    const gzip = child_process
      .execSync('gzip -9c | wc -c', { input: Buffer.from(bytes) })
      .toString()
      .trim()
    console.log(
      `${target.name.padEnd(10)} ${bytes.length} B wasm → ${
        Buffer.from(bytes).toString('base64').length
      } B base64 → ${gzip} B gzip (budget ${target.maxBytes} B)`,
    )
    files[target.out] = source
  }
  return files
}
