/**
 * Compiles src/tempo/internal/mine.c → WASM → base64 and writes mineWasm.ts.
 *
 * Requirements: LLVM clang with wasm32 target, wasm-opt (binaryen).
 *
 * Usage:
 *   pnpm tsx scripts/build-mine-wasm.ts
 */

import * as child_process from 'node:child_process'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const sourceFile = path.join(root, 'src/tempo/internal/mine.c')
const outputFile = path.join(root, 'src/tempo/internal/mine.wasm.ts')

function findTool(name: string, candidates: string[]): string {
  for (const candidate of candidates) {
    try {
      child_process.execSync(`${candidate} --version`, { stdio: 'ignore' })
      return candidate
    } catch {}
  }
  throw new Error(`Cannot find ${name}. Tried: ${candidates.join(', ')}`)
}

const clang = findTool('clang (with wasm32 target)', [
  '/opt/homebrew/opt/llvm/bin/clang', // macOS Homebrew
  '/usr/local/opt/llvm/bin/clang', // macOS Intel Homebrew
  'clang', // system PATH
])

const wasmOpt = findTool('wasm-opt (binaryen)', [
  'wasm-opt',
  '/opt/homebrew/bin/wasm-opt',
  '/usr/local/bin/wasm-opt',
])

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'mine-wasm-'))
const rawWasm = path.join(tmp, 'mine.wasm')
const optWasm = path.join(tmp, 'mine-opt.wasm')

try {
  console.log(`Compiling ${sourceFile}...`)
  child_process.execSync(
    [
      clang,
      '--target=wasm32',
      '-O3 -flto',
      '-nostdlib -fno-builtin -ffreestanding',
      '-Wl,--no-entry -Wl,--strip-all -Wl,--initial-memory=131072',
      '-Wl,--export=mine',
      `-o ${rawWasm}`,
      sourceFile,
    ].join(' '),
    { stdio: 'inherit' },
  )

  console.log('Optimizing with wasm-opt -O4...')
  child_process.execSync(`${wasmOpt} -O4 ${rawWasm} -o ${optWasm}`, {
    stdio: 'inherit',
  })

  const binary = new Uint8Array(fs.readFileSync(optWasm))
  const base64 = Buffer.from(binary).toString('base64')

  console.log(
    `WASM binary: ${binary.length} bytes → ${base64.length} chars base64`,
  )

  fs.writeFileSync(
    outputFile,
    `// Embedded TIP-1022 WASM keccak256 salt miner (compiled from mine.c).
//
// Memory layout at offset 1024:
//   [0..19]   address   (20 bytes, set by JS)
//   [20..51]  salt      (32 bytes, set/read by JS, incremented in-place)
//   [52..83]  hash out  (32 bytes, written on match)
//
// Exported: mine(count: i32) -> i32 — returns 1 if found, 0 if not.
//
// Generated by: pnpm tsx scripts/build-mine-wasm.ts

/** Base64-encoded WASM binary for the TIP-1022 salt miner. */
export const wasmBase64 =
  '${base64}'

/** Byte offset in WASM linear memory where mining I/O begins. */
export const dataOffset = 1024
`,
  )

  console.log(`Wrote ${outputFile}`)
} finally {
  if (fs.existsSync(tmp)) fs.rmSync(tmp, { recursive: true })
}
