// Builds the Ox EVM engine.
//
//   node --import tsx scripts/build-evm.ts          # wasm + base64 module
//   node --import tsx scripts/build-evm.ts --check   # verify committed output
//
// The wasm artifact is emitted as a base64 string inside a `.ts` module rather
// than as a binary asset. That is the same choice `src/tempo/internal/mine.wasm.ts`
// makes, and it is what keeps the package working under every bundler without a
// loader plugin, in Node, Bun, Deno, and browsers alike.
//
// `--check` exists because the salt miner's generator was never committed and
// its artifact cannot be reproduced. CI runs this so that never happens here.

import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const cDir = join(root, 'src/evm/internal/c')
const out = join(root, 'src/evm/internal/evm.wasm.ts')

const sources = ['evm.c']

/** Freestanding wasm32: no libc, no WASI, no imports. */
const wasmFlags = [
  '--target=wasm32',
  '-nostdlib',
  '-O3',
  '-flto',
  '-fno-builtin',
  '-Wall',
  '-Wextra',
  '-Wl,--no-entry',
  '-Wl,--export-dynamic',
  '-Wl,--export=__heap_base',
  '-Wl,--export-memory',
  '-Wl,--initial-memory=1048576',
  '-Wl,--max-memory=1073741824',
  '-Wl,--allow-undefined',
  '-Wl,--strip-all',
  '-Wl,--lto-O3',
]

function buildWasm(): Uint8Array {
  const dir = mkdtempSync(join(tmpdir(), 'ox-evm-'))
  try {
    const wasm = join(dir, 'evm.wasm')
    execFileSync(
      'clang',
      [...wasmFlags, ...sources.map((s) => join(cDir, s)), '-o', wasm],
      { stdio: 'inherit' },
    )
    return new Uint8Array(readFileSync(wasm))
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

function render(binary: Uint8Array): string {
  const base64 = Buffer.from(binary).toString('base64')
  return `// Embedded Ox EVM engine (compiled from internal/c/evm.c).
//
// Generated by: pnpm build:evm
// Do not edit by hand. CI verifies this file matches a fresh build.

/** Base64-encoded WASM binary for the EVM interpreter. */
export const wasmBase64 =
  '${base64}'

/** Size of the decoded WASM binary, in bytes. */
export const wasmSize = ${binary.length}
`
}

const binary = buildWasm()
const next = render(binary)

if (process.argv.includes('--check')) {
  const current = (() => {
    try {
      return readFileSync(out, 'utf8')
    } catch {
      return ''
    }
  })()
  if (current !== next) {
    console.error(
      `src/evm/internal/evm.wasm.ts is stale. Run \`pnpm build:evm\` and commit the result.`,
    )
    process.exit(1)
  }
  console.log(`evm.wasm.ts is up to date (${binary.length} bytes).`)
} else {
  writeFileSync(out, next)
  console.log(`Wrote ${out} (${binary.length} bytes wasm).`)
}
